image: dev-registry.abr.ru/all_image/gi/golang-swag:1.25.3

variables:
  GITLAB_PROJECT_URL: "https://orssource.abr.ru/golang/paperless_office.git"
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
  TEST_FILE: ${CI_PROJECT_NAME}_test
  URL_PREFIX: "paper"

stages:
  - lint
  #  - test
  - auto_test
  - to_test_server
  - del_test_server
  - prebuild
  - build
#  - deploy

include:
  - project: 'golang/cicd_template'
    file: 'rules.gitlab-ci.yml'
  - project: 'golang/cicd_template'
    file: 'golang_new/lint.yml'
  - project: 'golang/cicd_template'
    file: 'golang_new/auto_test.yml'
  - project: 'golang/cicd_template'
    file: 'golang_new/to_servers.yml'
  - project: 'golang/cicd_template'
    file: 'golang_new/prebuild.yml'
  - project: 'golang/cicd_template'
    file: 'golang_new/build.yml'
#  - project: 'golang/cicd_template'
#    file: 'golang_new/test.yml'
