version: "2"
run:
  concurrency: 4
  go: 1.25.0
  issues-exit-code: 1
  tests: true
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - decorder
    - dogsled
    - dupword
    - durationcheck
    - errcheck
    - ginkgolinter
    - gocheckcompilerdirectives
    - gocritic
    - govet
    - ineffassign
    - staticcheck
    - unused
    - contextcheck
  settings:
    govet:
      enable-all: true
    nolintlint:
      require-explanation: true
      require-specific: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$